spring:
  cloud:
    stream:
      function:
        definition : orderSupplier
      bindings:
        orderSupplier-out-0: # out means producer
          destination: order-event

server:
  port: 8081
