spring:
  cloud:
    stream:
      function:
        definition : orderSupplier;paymentEventConsumer
      bindings:
        orderSupplier-out-0: # out means producer
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event
server:
  port: 8081
